language: csharp
mono: none
dotnet: 2.1.300
solution: CyLR.sln
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
    # - os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y curl coreutils ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install curl ; fi

script:
  - dotnet restore
  - dotnet test ./CyLRTests/

# Building linux version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir /home/travis/build/orlikoski/CyLR/deployments ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -Lo /home/travis/build/orlikoski/CyLR/warp-packer-linux https://github.com/dgiagio/warp/releases/download/v0.2.1/linux-x64.warp-packer ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x /home/travis/build/orlikoski/CyLR/warp-packer-linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet build -c release -r linux-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet publish -c release -r linux-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /home/travis/build/orlikoski/CyLR/warp-packer-linux --arch linux-x64 --input_dir /home/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/linux-x64/publish/ --exec CyLR --output /home/travis/build/orlikoski/CyLR/deployments/CyLR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -j /home/travis/build/orlikoski/CyLR/CyLR_linux.zip /home/travis/build/orlikoski/CyLR/deployments/CyLR ; fi

# Using Linux to Build Windows Packages until Travis-CI supports Windows containes for .NET Core
# Windows 64-bit version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet build -c release -r win-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet publish -c release -r win-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -j /home/travis/build/orlikoski/CyLR/CyLR_windows_x64.zip /home/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/win-x64/publish/* ; fi

# Windows 32-bit version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet build -c release -r win-x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet publish -c release -r win-x86 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -j /home/travis/build/orlikoski/CyLR/CyLR_windows_x86.zip /home/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/win-x86/publish/* ; fi

# Building Macos version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir /Users/travis/build/orlikoski/CyLR/deployments ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -Lo /Users/travis/build/orlikoski/CyLR/warp-packer-osx https://github.com/dgiagio/warp/releases/download/v0.2.1/macos-x64.warp-packer ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x /Users/travis/build/orlikoski/CyLR/warp-packer-osx ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  dotnet build -c release -r osx-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  dotnet publish -c release -r osx-x64 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /Users/travis/build/orlikoski/CyLR/warp-packer-osx --arch macos-x64 --input_dir /Users/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/osx-x64/publish/ --exec CyLR --output /Users/travis/build/orlikoski/CyLR/deployments/CyLR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -j /Users/travis/build/orlikoski/CyLR/CyLR_osx.zip /Users/travis/build/orlikoski/CyLR/deployments/CyLR ; fi

  # Keeping Windows build process draft for when Travis-CI supoorts it
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then  mkdir C:/Users/travis/build/orlikoski/CyLR/deployments ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -Lo ./warp-packer.exe https://github.com/dgiagio/warp/releases/download/v0.2.1/windows-x64.warp-packer ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet build -c release -r windows-x64 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet publish -c release -r windows-x64 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./warp-packer.exe --arch windows-x64 --input_dir bin/release/netcoreapp2.1/windows-x64/publish --exec CyLR.exe --output /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then zip -j /Users/travis/build/orlikoski/CyLR/CyLR_windowsx64.zip /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  #
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet build -c release -r windows-x86 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet publish -c release -r windows-x86 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./warp-packer.exe --arch windows-x64 --input_dir bin/release/netcoreapp2.1/windows-x64/publish --exec CyLR.exe --output /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then zip -j /Users/travis/build/orlikoski/CyLR/CyLR_windowsx64.zip /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi

deploy:
  provider: releases
  api_key:
    secure: F3vanioKwtxsaSldx+I5mpzeXnAmRu4IK4eun7nk/UXRz+X3eruqhRp1zJoc0zhh34CQ2UqfsQpebjuBTD7ho1wkdlmMLFeuqmV+vFM5Or/qcWiVygI5h/OWXdUJbRCe/XR9fy5BxH8QNWoLQ4qaLzItl4pnMi6DaEvWS4VHP5RNZZ2KvNJq4aAc/5DMONpenyMMJNvgozf0pVXnwN9BF9CiUQIpBTYg71VLOco/4NtMvxgiyKREt/mMS/lbv0v/KizYmrgJDAHincsWqI/Rj5nLaZIZDMcQma+WKldwOy9EPZnWlmXmSwDpQPS+tw+qx6vvOJc0r24rjBUZCpCPeY6pMYnO7VXeHD75HAc7b49Wg+0nHL69EsSY2VdJY6Oka7hGaQB9MmvxSQW9j4/YfoLmXW7Cl++EKm1m6SADVe9BRVnkQ0q5Aw9VD8Q+aJxh75E3yaGW9Uc5kwLHX0kdu5jz+gKd/XswHBqYQp7wO/ziObaCJtFwMiOzK1EpdEdsBqaKiBVKw1HBft1wGusLBAr1oKsowqwan8PhjR2r/3U11MGNECQgbxe6/iLSJ+p7J79kS0M1phsx/HeAuANi3BSmh5i3Dv0FzI9Ny4ViKnAx7eoJXTfIgKSXQx3YmwZwMrUH+djd4RekGRQwzAv744x3HkAz1C0/EYKIGR4xShs=
  file:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./orlikoski/CyLR/CyLR_linux.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./orlikoski/CyLR/CyLR_osx.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /Users/travis/build/orlikoski/CyLR/CyLR_windows_x86.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /Users/travis/build/orlikoski/CyLR/CyLR_windows_x64.zip ; fi
  skip_cleanup: true
  on:
    tags: true
