language: csharp
mono: none
dotnet: 2.1.300
solution: CyLR.sln
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: 
        - BUILD_ARCH=linux-x64
        - USE_WARP=true
    - os: osx
      env:
        - BUILD_ARCH=osx-x64
        - USE_WARP=true
    - os: linux
      dist: xenial
      sudo: required
      env: 
        - BUILD_ARCH=win-x64
        - USE_WARP=false
    - os: linux
      dist: xenial
      sudo: required
      env:
        - BUILD_ARCH=win-x86
        - USE_WARP=false
#    - os: windows

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y curl coreutils ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install curl ; fi

script: 
  - scripts/test.sh
  - scripts/build.sh
  - scripts/package.sh

#   - dotnet restore
#   - dotnet test ./CyLRTests/


# Using Linux to Build Windows Packages until Travis-CI supports Windows containers for .NET Core
# Windows 64-bit version
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet build -c release -r win-x64 ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet publish -c release -r win-x64 ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -j /home/travis/build/orlikoski/CyLR/CyLR_windows_x64.zip /home/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/win-x64/publish/* ; fi

# # Windows 32-bit version
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet build -c release -r win-x86 ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dotnet publish -c release -r win-x86 ; fi
#   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -j /home/travis/build/orlikoski/CyLR/CyLR_windows_x86.zip /home/travis/build/orlikoski/CyLR/CyLR/bin/Release/netcoreapp2.1/win-x86/publish/* ; fi


  # Keeping Windows build process draft for when Travis-CI supoorts it
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then  mkdir C:/Users/travis/build/orlikoski/CyLR/deployments ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -Lo ./warp-packer.exe https://github.com/dgiagio/warp/releases/download/v0.2.1/windows-x64.warp-packer ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet build -c release -r windows-x64 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet publish -c release -r windows-x64 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./warp-packer.exe --arch windows-x64 --input_dir bin/release/netcoreapp2.1/windows-x64/publish --exec CyLR.exe --output /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then zip -j /Users/travis/build/orlikoski/CyLR/CyLR_windowsx64.zip /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  #
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet build -c release -r windows-x86 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then dotnet publish -c release -r windows-x86 ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./warp-packer.exe --arch windows-x64 --input_dir bin/release/netcoreapp2.1/windows-x64/publish --exec CyLR.exe --output /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then zip -j /Users/travis/build/orlikoski/CyLR/CyLR_windowsx64.zip /Users/travis/build/orlikoski/CyLR/deployments/CyLRx64.exe ; fi

deploy:
  provider: releases
  api_key:
    secure: F3vanioKwtxsaSldx+I5mpzeXnAmRu4IK4eun7nk/UXRz+X3eruqhRp1zJoc0zhh34CQ2UqfsQpebjuBTD7ho1wkdlmMLFeuqmV+vFM5Or/qcWiVygI5h/OWXdUJbRCe/XR9fy5BxH8QNWoLQ4qaLzItl4pnMi6DaEvWS4VHP5RNZZ2KvNJq4aAc/5DMONpenyMMJNvgozf0pVXnwN9BF9CiUQIpBTYg71VLOco/4NtMvxgiyKREt/mMS/lbv0v/KizYmrgJDAHincsWqI/Rj5nLaZIZDMcQma+WKldwOy9EPZnWlmXmSwDpQPS+tw+qx6vvOJc0r24rjBUZCpCPeY6pMYnO7VXeHD75HAc7b49Wg+0nHL69EsSY2VdJY6Oka7hGaQB9MmvxSQW9j4/YfoLmXW7Cl++EKm1m6SADVe9BRVnkQ0q5Aw9VD8Q+aJxh75E3yaGW9Uc5kwLHX0kdu5jz+gKd/XswHBqYQp7wO/ziObaCJtFwMiOzK1EpdEdsBqaKiBVKw1HBft1wGusLBAr1oKsowqwan8PhjR2r/3U11MGNECQgbxe6/iLSJ+p7J79kS0M1phsx/HeAuANi3BSmh5i3Dv0FzI9Ny4ViKnAx7eoJXTfIgKSXQx3YmwZwMrUH+djd4RekGRQwzAv744x3HkAz1C0/EYKIGR4xShs=
  file:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /home/travis/build/orlikoski/CyLR/CyLR_linux.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /Users/travis/build/orlikoski/CyLR/CyLR_osx.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /home/travis/build/orlikoski/CyLR/CyLR_windows_x86.zip ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /home/travis/build/orlikoski/CyLR/CyLR_windows_x64.zip ; fi
  skip_cleanup: true
  on:
    tags: true
